[project]
name = "mux"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.121.3",
    "letta-client>=1.1.2",
    "openai>=2.8.1",
    "pydantic>=2.12.4",
    "uvicorn>=0.38.0",
]
